services:

  php-demo:
    image: dunglas/frankenphp:latest-alpine 
    container_name: frankenphp              
    restart: unless-stopped
    ports:
      - "${PORT}:80"                   
    volumes:                          
      - ./demo:/etc/demo:ro
      - ./Caddyfile:/etc/caddy/Caddyfile:ro    
      - frankenphp_data:/data               # Line to modify: Persistent storage for TLS certificates
      - frankenphp_config:/config           # Line to modify: Persistent storage for Caddy configurations
    environment:
      SERVER_NAME: ":80"                   
    env_file:
      - .env


  stemsplitter-api:
    build:
      context: .
      dockerfile_inline: |
        FROM beveradb/audio-separator:gpu-0.44.5
        WORKDIR /app
        RUN pip install --no-cache-dir "fastapi[standard]" hypercorn uvloop httpx rq redis
        ENTRYPOINT []
    environment:
      PYTHONPYCACHEPREFIX: /tmp/pycache
      REDIS_HOST: redis
    depends_on:
      - redis
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: "no"
    volumes:
      - ./src:/app:z
      - /tmp/asep/exports:/etc/exports:Z
      - /tmp/asep/models:/etc/models:Z
    env_file:
      - .env

    command: sh -c "rq worker audio-processing & hypercorn index:app --bind 0.0.0.0:8000 --reload"

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    command: redis-server --save "" --appendonly no
    volumes:
      - /tmp/redis_data:/data
    env_file:
      - .env

volumes:
  frankenphp_data:
  frankenphp_config:



    