services:
  caddy:
    build: 
      context: dockerfile
      dockerfile: caddy.df
    container_name: caddy            
    # restart: unless-stopped
    ports:
      - "${PORT}:80"                   
    volumes:                          
      - ./demo:/etc/demo:z
      - ./Caddyfile:/etc/caddy/Caddyfile:z   
    environment:
      SERVER_NAME: ":80"                   
    env_file:
      - .env
    command: caddy run --config /etc/caddy/Caddyfile


  stemsplitter-api:
    build:
      context: dockerfile
      dockerfile: stemsplitter.df
    environment:
      REDIS_HOST: redis
      PYTHONPYCACHEPREFIX: /tmp/pycache
      MODE: ${MODE}
    depends_on:
      - redis
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: "no"
    volumes:
      - ./src:/app:z
      - /tmp/asep/exports:/etc/exports:Z
      - /tmp/asep/models:/etc/models:Z
    env_file:
      - .env

    command: sh -c "rq worker audio-processing & hypercorn index:app --bind 0.0.0.0:8000 ${MODE:+$( [ "$MODE" = "DEV" ] && echo "--reload" )}"

  redis:
    image: redis:alpine
    container_name: redis
    # restart: unless-stopped
    command: redis-server --save "" --appendonly no
    volumes:
      - /tmp/redis_data:/data
    env_file:
      - .env



    