services:
  caddy:
    image: caddy:2.11-alpine
    container_name: caddy
    restart: unless-stopped
    # Gives Caddy the permission to bind to low ports like 80/443 inside Linux environments
    cap_add:
      - NET_ADMIN
    ports:
      - "8000:80"       # HTTP
      - "443:443"     # HTTPS (TCP)
      - "443:443/udp" # HTTP/3 / QUIC support (Highly Recommended)
    volumes:
      # Mount your configuration file (read-only for security)
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      # CRUCIAL: Persistent volumes for Let's Encrypt certificates and configuration state
      - /tmp/caddy_data:/data
      - /tmp/caddy_config:/config
      - ${PWD}/res:/res


  stemsplitter-api:
    build:
      context: .
      dockerfile_inline: |
        FROM beveradb/audio-separator:gpu-0.44.5
        WORKDIR /app
        RUN pip install --no-cache-dir "fastapi[standard]" hypercorn uvloop httpx rq redis
        ENTRYPOINT []
    env_file:
      - .env
    environment:
      PYTHONPYCACHEPREFIX: /tmp/pycache
      REDIS_HOST: redis
    depends_on:
      - redis
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: "no"
    volumes:
      - ./src:/app:z
      - /tmp/exports:/etc/exports:Z
      - /tmp/models:/etc/models:Z

    command: sh -c "rq worker audio-processing & hypercorn index:app --bind 0.0.0.0:8000 --reload"

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - /tmp/redis_data:/data
    



    